[project]
name = "template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.0.2",
    "neovim>=0.3.1",
    "pip>=25.0.1",
    "pynvim>=0.5.2",
    "sqlfluff>=3.3.1",
    "visidata>=3.1.1",
]

[tool.sqlfluff.core]
dialect = "bigquery"
rules = "all"
output_line_length = 120
processes = -1
exclude_rules = "RF01"
max_line_length = 120
large_file_skip_byte_limit = 0
[tool.sqlfluff.indentation]
indented_joins = false
indent_using_on = true
template_blocks_indent = false
indent_unit = "space"
tab_space_size = 4

