[project]
name = "global-alumni"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
	"absl-py",
	"aiohappyeyeballs",
	"aiohttp",
	"aiohttp-retry",
	"aiosignal",
	"altair",
	"amqp",
	"anyio",
	"appdirs",
	"appnope",
	"argon2-cffi",
	"argon2-cffi-bindings",
	"arrow",
	"asttokens",
	"astunparse",
	"async-lru",
	"asyncssh",
	"atpublic",
	"attrs",
	"autovizwidget",
	"babel",
	"bcrypt",
	"beautifulsoup4",
	"bigquery-magics",
	"billiard",
	"bleach",
	"blinker",
	"blosc",
	"bokeh",
	"boto3",
	"botocore",
	"brotli",
	"cachetools",
	"catalogue",
	"celery",
	"certifi",
	"cffi",
	"chardet",
	"charset-normalizer",
	"clang",
	"click",
	"click-didyoumean",
	"click-plugins",
	"click-repl",
	"cligj",
	"cloudpathlib",
	"cloudpickle",
	"colorama",
	"colorcet",
	"comm",
	"confection",
	"configobj",
	"contourpy",
	"cramjam>=2.9.1",
	"cryptography",
	"cssselect2",
	"cycler",
	"cymem",
	"cython",
	"cytoolz",
	"dask",
	"dask-expr",
	"datasets",
	"dateutils",
	"db-dtypes",
	"debugpy",
	"decorator",
	"defusedxml",
	"dictdiffer",
	"dill",
	"diskcache",
	"distributed",
	"distro",
	"dlt",
	"dnspython",
	"docx2txt",
	"dpath",
	"duckdb",
	"duckdb-engine",
	"dulwich",
	"dvc",
	"dvc-data",
	"dvc-http",
	"dvc-objects",
	"dvc-render",
	"dvc-studio-client",
	"dvc-task",
	"dvclive",
	"emoji",
	"entrypoints",
	"et_xmlfile",
	"evaluate",
	"exceptiongroup",
	"executing",
	"fastavro",
	"fasteners",
	"fastexcel",
	"filelock",
	"fiona",
	"fire",
	"flask",
	"flatbuffers",
	"flatten-dict",
	"flufl-lock",
	"flufl.lock",
	"fmt",
	"frozendict",
	"frozenlist",
	"fsspec",
	"funcy",
	"future",
	"fuzzywuzzy",
	"gapstatistics",
	"gast",
	"gensim",
	"geopandas",
	"geos",
	"geotiff",
	"gitdb",
	"gitpython",
	"giturlparse",
	"glog",
	"gmp",
	"google-api-core",
	"google-api-python-client",
	"google-apitools",
	"google-auth",
	"google-auth-httplib2",
	"google-auth-oauthlib",
	"google-cloud-bigquery",
	"google-cloud-bigquery-datatransfer",
	"google-cloud-bigquery-storage",
	"google-cloud-core",
	"google-crc32c",
	"google-pasta",
	"google-resumable-media",
	"googleapis-common-protos",
	"googletrans",
	"grandalf",
	"graphite2",
	"graphviz",
	"greenlet",
	"grpcio",
	"grpcio-status",
	"gsl",
	"gto",
	"h11",
	"h2",
	"h5py",
	"hdijupyterutils",
	"hexbytes",
	"holoviews",
	"hpack",
	"hstspreload",
	"html2text",
	"html5lib",
	"httpcore",
	"httplib2",
	"httpx",
	"huggingface_hub",
	"humanize",
	"hvplot",
	"hydra-core",
	"hyperframe",
	"icon-font-to-png",
	"icu",
	"idna",
	"imageio",
	"importlib_metadata",
	"importlib_resources",
	"ipykernel",
	"ipympl",
	"ipython",
	"ipython_genutils",
	"ipywidgets",
	"isoduration",
	"itables",
	"iterative-telemetry",
	"itsdangerous",
	"jedi",
	"jinja2",
	"jmespath",
	"joblib",
	"json5",
	"jsonpath-ng",
	"jsonpointer",
	"jsonschema",
	"jsonschema-specifications",
	"jupyter",
	"jupyter-lsp",
	"jupyter_client",
	"jupyter_console",
	"jupyter_core",
	"jupyter_events",
	"jupyter_server",
	"jupyter_server_terminals",
	"jupyterlab",
	"jupyterlab_pygments",
	"jupyterlab_server",
	"jupyterlab_widgets",
	"kiwisolver",
	"kneed",
	"kombu",
	"krb5",
	"langcodes",
	"lazy-loader",
	"lerc",
	"libclang",
	"lime",
	"llvmlite",
	"locket",
	"loguru>=0.7.3",
	"lxml",
	"make",
	"makefun",
	"markdown",
	"markdown-it-py",
	"markupsafe",
	"matplotlib",
	"matplotlib-inline",
	"mdit-py-plugins",
	"mdurl",
	"mistune",
	"ml-dtypes",
	"mlxtend",
	"mock",
	"mpfr",
	"mpmath",
	"msgpack-python",
	"multidict",
	"multiprocess",
	"multitasking",
	"munkres",
	"murmurhash",
	"mysql-connector-python",
	"namex",
	"narwhals",
	"nbclassic",
	"nbclient",
	"nbformat",
	"nest-asyncio",
	"networkx",
	"nltk",
	"nose",
	"notebook",
	"notebook-shim",
	"nss",
	"numba",
	"numpy",
	"oauth2client",
	"oauthlib",
	"omegaconf",
	"openai",
	"openpyxl",
	"opt-einsum",
	"optree",
	"orc",
	"orjson",
	"outcome",
	"overrides",
	"packaging",
	"palettable",
	"pandas",
	"pandocfilters",
	"panel",
	"pango",
	"param",
	"paramiko",
	"parso",
	"partd",
	"pathlib2",
	"pathspec",
	"pathvalidate",
	"patsy",
	"pcre2",
	"peewee",
	"pendulum",
	"pexpect",
	"pickleshare",
	"pillow",
	"pip",
	"pkgutil-resolve-name",
	"platformdirs",
	"plotly",
	"ply",
	"polars",
	"preshed",
	"proj",
	"prometheus_client",
	"prompt_toolkit",
	"proto-plus==1.24.0.dev1",
	"protobuf",
	"psutil",
	"psycopg",
	"psycopg-binary>=3.2.4",
	"psycopg-c>=3.2.4",
	"psycopg-pool",
	"psycopg2",
	"psycopg2-binary",
	"ptyprocess",
	"pure_eval",
	"py4j",
	"pyarrow",
	"pyarrow-hotfix",
	"pyasn1",
	"pyasn1-modules",
	"pycairo",
	"pycparser",
	"pydantic",
	"pydantic-core",
	"pydata-google-auth",
	"pydeck",
	"pydot",
	"pydyf",
	"pygit2",
	"pygments",
	"pygtrie",
	"pyjwt",
	"pylatexenc>=2.10",
	"pymining",
	"pymongo",
	"pynacl",
	"pynvim",
	"pynvml",
	"pyobjc-core",
	"pyobjc-framework-cocoa",
	"pyopenssl",
	"pyparsing",
	"pypdf2",
	"pyphen",
	"pyproj",
	"pysocks",
	"pyspark",
	"python-dateutil",
	"python-dotenv",
	"python-gssapi",
	"python-json-logger",
	"python-levenshtein",
	"pytz",
	"pyu2f",
	"pyviz_comms",
	"pyyaml",
	"pyzmq",
	"qgrid",
	"quipus>=0.3.2",
	"rapidfuzz",
	"referencing",
	"regex",
	"reportlab",
	"requests",
	"requests-oauthlib",
	"rich",
	"rlpycairo",
	"rpds-py",
	"rsa",
	"rtree",
	"s3transfer",
	"scikit-learn",
	"scmrepo",
	"seaborn",
	"seaborn-base",
	"selenium",
	"semver",
	"send2trash",
	"setuptools",
	"shapely",
	"shellingham",
	"shortuuid",
	"shtab",
	"sigtool",
	"simplejson",
	"six",
	"slicer",
	"smart_open",
	"smmap",
	"snappy",
	"sniffio",
	"sortedcontainers",
	"soupsieve",
	"spacy",
	"spacy-legacy",
	"spacy-loggers",
	"spdlog",
	"sqlalchemy",
	"sqlfluff>=3.3.0",
	"sqltrie",
	"srsly",
	"stack_data",
	"statsmodels>=0.14.4",
	"streamlit",
	"stylecloud",
	"sympy",
	"tabulate",
	"tapi",
	"tblib",
	"tenacity",
	"termcolor",
	"terminado",
	"thinc",
	"threadpoolctl",
	"tifffile",
	"tiktoken>=0.8.0",
	"tiledb",
	"time-machine",
	"tinycss",
	"tinycss2",
	"tk",
	"tktable",
	"toml",
	"tomli",
	"tomlkit",
	"toolz",
	"tornado",
	"tqdm",
	"traitlets",
	"transformers>=4.47.1",
	"trio",
	"trio-websocket",
	"typer",
	"types-python-dateutil",
	"typing>=3.10.0.0",
	"typing_extensions",
	"typing_utils",
	"tzlocal",
	"uc-micro-py",
	"unidecode",
	"uri-template",
	"uritemplate",
	"urllib3",
	"validators",
	"vine",
	"visidata",
	"voluptuous",
	"wasabi",
	"watchdog",
	"wcwidth",
	"weasel",
	"webcolors",
	"webencodings",
	"websocket-client",
	"wheel",
	"widgetsnbextension",
	"wordcloud",
	"wsproto",
	"xgboost",
	"xlrd",
	"xlsxwriter",
	"xyzservices",
	"yarl",
	"zc.lockfile",
	"zict",
	"zipp",
	"zstandard",
	"zstd",
]

[tool.sqlfluff.core]
dialect = "bigquery"
rules = "all"
output_line_length = 120
processes = -1
exclude_rules = "RF01"
max_line_length = 120
large_file_skip_byte_limit = 0
[tool.sqlfluff.indentation]
indented_joins = false
indent_using_on = true
template_blocks_indent = false
indent_unit = "tab"
tab_space_size = 4
